### ISSUE TITLE
Vaadetes (esileht, klassiruumid, lõpuekraan) pildid vahetada

### ISSUE THREAD

**Issue by rmuld** [TLUHK-Portfolio/Mina-Tean#97]
Me tahame, et disainis tehtud muudatused oleksid mängu implementeeritud.

Kriteeriumid:
- [x] esileht on uuendatud vastavalt uuele disainile #91 
- [x] lõpuekraan on uuendatud vastavalt uuele disainile #92 
- [x] klassiruumide kuva on uuendatud vastavalt uuele disainile #101
